services:
    core-service:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: core-service
        command: npm run start:dev
        ports:
            - 3000:3000
        env_file: .env
        volumes:
            - ./:/app
        depends_on:
            - postgres-core-service
        environment:
            - npm_config_cache=/home/node/.npm
        user: '${DOCKER_UID:-node}:${DOCKER_GID:-node}'

    postgres-core-service:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=core-service
        ports:
            - 54321:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgadmin-core-service:
        image: dpage/pgadmin4:8.11
        environment:
            - PGADMIN_DEFAULT_EMAIL=local@test.com
            - PGADMIN_DEFAULT_PASSWORD=Test@123
            - PGADMIN_LISTEN_PORT=5050
        ports:
            - 5050:5050
        volumes:
            - pgadmin-data:/var/lib/pgadmin

volumes:
    postgres-data:
    pgadmin-data:
